"use client";
import { create } from "zustand";
import { devtools } from "zustand/middleware";
import {
  getDieticianAssociationAPI,
  type AcademicsPagedRequest,
  type AcademicsPagedResponseDto,
} from "../services/generated";
import { handleError, cachedFetch } from "./storeUtils";
import { toast } from "@/hooks/use-toast";

const api = getDieticianAssociationAPI();

// Types (will be generated by OpenAPI)
type UniversityDto = any;
type CollegeDto = any;
type CollegeTypeDto = any;
type DistrictDto = any;
type CreateUniversityDto = any;
type UpdateUniversityDto = any;
type CreateCollegeDto = any;
type UpdateCollegeDto = any;

interface EducationState {
  // Universities
  universities: UniversityDto[];
  selectedUniversity: UniversityDto | null;
  
  // Colleges
  colleges: CollegeDto[];
  selectedCollege: CollegeDto | null;
  
  // Reference data
  collegeTypes: CollegeTypeDto[];
  districts: DistrictDto[];
  
  // UI state
  loading: boolean;
  error: string | null;
  success: boolean;
  message: string | null;
  currentTab: "universities" | "colleges";
  academicsData: AcademicsPagedResponseDto | null;

  // University actions
  fetchUniversities: () => Promise<void>;
  fetchUniversityById: (id: number) => Promise<void>;
  createUniversity: (data: CreateUniversityDto) => Promise<void>;
  updateUniversity: (id: number, data: UpdateUniversityDto) => Promise<void>;
  deleteUniversity: (id: number) => Promise<void>;

  // College actions
  fetchColleges: () => Promise<void>;
  fetchCollegesByUniversity: (universityId: number) => Promise<void>;
  fetchCollegeById: (id: number) => Promise<void>;
  createCollege: (data: CreateCollegeDto) => Promise<void>;
  updateCollege: (id: number, data: UpdateCollegeDto) => Promise<void>;
  deleteCollege: (id: number) => Promise<void>;

  // Reference data actions
  fetchCollegeTypes: () => Promise<void>;
  fetchDistrictsByState: (stateId: number) => Promise<void>;
  fetchAcademicsPaginated: (request: AcademicsPagedRequest) => Promise<AcademicsPagedResponseDto>;

  // UI actions
  setCurrentTab: (tab: "universities" | "colleges") => void;
  clearMessage: () => void;
}

export const useEducationStore = create<EducationState>()(
  devtools((set, get) => ({
    universities: [],
    selectedUniversity: null,
    colleges: [],
    selectedCollege: null,
    collegeTypes: [],
    districts: [],
    loading: false,
    error: null,
    success: false,
    message: null,
    currentTab: "universities",
    academicsData: null,

    // University actions
    fetchUniversities: async () => {
      set({ loading: true, error: null });
      try {
        const result = await api.getApiEducationUniversities();
        set({
          universities: result.data,
          loading: false,
        });
      } catch (err) {
        const error = handleError(err);
        set({ error, loading: false });
        toast({
          title: "Error",
          description: error,
          variant: "error",
        });
      }
    },

    fetchUniversityById: async (id: number) => {
      set({ loading: true, error: null });
      try {
        const result = await api.getApiEducationUniversitiesId(id);
        set({
          selectedUniversity: result.data,
          loading: false,
        });
      } catch (err) {
        const error = handleError(err);
        set({ error, loading: false });
        toast({
          title: "Error",
          description: error,
          variant: "error",
        });
      }
    },

    createUniversity: async (data: CreateUniversityDto) => {
      set({ loading: true, error: null, success: false, message: null });
      try {
        const result = await api.postApiEducationUniversities(data);
        set((state) => ({
          universities: [...state.universities, result.data],
          loading: false,
          success: true,
          message: "University created successfully",
        }));
        toast({
          title: "Success",
          description: "University created successfully",
          variant: "success",
        });
      } catch (err) {
        const error = handleError(err);
        set({ error, loading: false, success: false });
        toast({
          title: "Error",
          description: error,
          variant: "error",
        });
      }
    },

    updateUniversity: async (id: number, data: UpdateUniversityDto) => {
      set({ loading: true, error: null, success: false, message: null });
      try {
        const result = await api.putApiEducationUniversitiesId(id, data);
        set((state) => ({
          universities: state.universities.map((u) =>
            u.id === id ? result.data : u
          ),
          loading: false,
          success: true,
          message: "University updated successfully",
        }));
        toast({
          title: "Success",
          description: "University updated successfully",
          variant: "success",
        });
      } catch (err) {
        const error = handleError(err);
        set({ error, loading: false, success: false });
        toast({
          title: "Error",
          description: error,
          variant: "error",
        });
      }
    },

    deleteUniversity: async (id: number) => {
      set({ loading: true, error: null, success: false, message: null });
      try {
        await api.deleteApiEducationUniversitiesId(id);
        set((state) => ({
          universities: state.universities.filter((u) => u.id !== id),
          loading: false,
          success: true,
          message: "University deleted successfully",
        }));
        toast({
          title: "Success",
          description: "University deleted successfully",
          variant: "success",
        });
      } catch (err) {
        const error = handleError(err);
        set({ error, loading: false, success: false });
        toast({
          title: "Error",
          description: error,
          variant: "error",
        });
      }
    },

    // College actions
    fetchColleges: async () => {
      set({ loading: true, error: null });
      try {
        const result = await api.getApiEducationColleges();
        set({
          colleges: result.data,
          loading: false,
        });
      } catch (err) {
        const error = handleError(err);
        set({ error, loading: false });
        toast({
          title: "Error",
          description: error,
          variant: "error",
        });
      }
    },

    fetchCollegesByUniversity: async (universityId: number) => {
      set({ loading: true, error: null });
      try {
        const result = await api.getApiEducationCollegesUniversityUniversityId(universityId);
        set({
          colleges: result.data,
          loading: false,
        });
      } catch (err) {
        const error = handleError(err);
        set({ error, loading: false });
        toast({
          title: "Error",
          description: error,
          variant: "error",
        });
      }
    },

    fetchCollegeById: async (id: number) => {
      set({ loading: true, error: null });
      try {
        const result = await api.getApiEducationCollegesId(id);
        set({
          selectedCollege: result.data,
          loading: false,
        });
      } catch (err) {
        const error = handleError(err);
        set({ error, loading: false });
        toast({
          title: "Error",
          description: error,
          variant: "error",
        });
      }
    },

    createCollege: async (data: CreateCollegeDto) => {
      set({ loading: true, error: null, success: false, message: null });
      try {
        const result = await api.postApiEducationColleges(data);
        set((state) => ({
          colleges: [...state.colleges, result.data],
          loading: false,
          success: true,
          message: "College created successfully",
        }));
        toast({
          title: "Success",
          description: "College created successfully",
          variant: "success",
        });
      } catch (err) {
        const error = handleError(err);
        set({ error, loading: false, success: false });
        toast({
          title: "Error",
          description: error,
          variant: "error",
        });
      }
    },

    updateCollege: async (id: number, data: UpdateCollegeDto) => {
      set({ loading: true, error: null, success: false, message: null });
      try {
        const result = await api.putApiEducationCollegesId(id, data);
        set((state) => ({
          colleges: state.colleges.map((c) =>
            c.id === id ? result.data : c
          ),
          loading: false,
          success: true,
          message: "College updated successfully",
        }));
        toast({
          title: "Success",
          description: "College updated successfully",
          variant: "success",
        });
      } catch (err) {
        const error = handleError(err);
        set({ error, loading: false, success: false });
        toast({
          title: "Error",
          description: error,
          variant: "error",
        });
      }
    },

    deleteCollege: async (id: number) => {
      set({ loading: true, error: null, success: false, message: null });
      try {
        await api.deleteApiEducationCollegesId(id);
        set((state) => ({
          colleges: state.colleges.filter((c) => c.id !== id),
          loading: false,
          success: true,
          message: "College deleted successfully",
        }));
        toast({
          title: "Success",
          description: "College deleted successfully",
          variant: "success",
        });
      } catch (err) {
        const error = handleError(err);
        set({ error, loading: false, success: false });
        toast({
          title: "Error",
          description: error,
          variant: "error",
        });
      }
    },

    // Reference data actions
    fetchCollegeTypes: async () => {
      if (get().collegeTypes.length > 0) return;
      try {
        const collegeTypes = await cachedFetch(
          'education:collegeTypes',
          async () => {
            const result = await api.getApiEducationCollegeTypes();
            return result.data;
          },
          5 * 60_000
        );
        set({ collegeTypes });
      } catch (err) {
        const error = handleError(err);
        console.error("Error fetching college types:", error);
      }
    },

    fetchDistrictsByState: async (stateId: number) => {
      set({ districts: [] });
      try {
        const districts = await cachedFetch(
          `education:districts:${stateId}`,
          async () => {
            const result = await api.getApiEducationDistrictsStateStateId(stateId);
            return result.data;
          },
          5 * 60_000
        );
        set({ districts });
      } catch (err) {
        const error = handleError(err);
        console.error("Error fetching districts:", error);
        toast({
          title: "Error",
          description: error,
          variant: "error",
        });
      }
    },

    fetchAcademicsPaginated: async (request: AcademicsPagedRequest) => {
      set({ loading: true, error: null });
      try {
        const result = await api.postApiEducationAcademicsPaginated(request);
        set({ academicsData: result.data, loading: false });
        return result.data;
      } catch (err) {
        const error = handleError(err);
        set({ error, loading: false });
        toast({
          title: "Error",
          description: error,
          variant: "error",
        });
        throw err;
      }
    },

    // UI actions
    setCurrentTab: (tab: "universities" | "colleges") => set({ currentTab: tab }),
    clearMessage: () => set({ message: null, success: false, error: null }),
  }))
);
