// <auto-generated />
using System;
using DieticianAssociation.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DieticianAssociation.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250830130000_MarkPreviousMigrationsAsApplied")]
    partial class MarkPreviousMigrationsAsApplied
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is a dummy migration just to mark previous migrations as applied
            // No model changes
        }
    }
}
